"""
Authentic ACCU DESIGN Quotation Generator

Matches the exact layout from the provided Image 3 reference.
  - Symmetrical, proper positioning, no off-center boxes
  - Header with Logo top-right
  - Stacked Date/Quote No on the left
  - Table: Sr#, DESCRIPTION, DIMENSIONS, CATEGORY, PART NO, MATERIAL, QTY, Weight(kg), MANUFACTURING PROCESS, Cost
  - Totals: Appended cleanly to the bottom of the table
  - Grand total and Amount in Words highlighted in lime-green
  - Footer with double line separator
  - Full Unicode support for exact formatting (₹ symbol)
"""

import tempfile
import base64
import math
import os
from fpdf import FPDF
from datetime import datetime

try:
    from services.quote_number import amount_in_words
except ImportError:
    from quote_number import amount_in_words

# ── Resolve paths ────────────────────────────────────────────────────────────
BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BACKEND_DIR, "assets")
LOGO_PATH = os.path.join(ASSETS_DIR, "logo.png")

# ── Windows font paths (for Unicode ₹ support) ──────────────────────────────
FONT_DIR = r"C:\Windows\Fonts"
ARIAL_REGULAR = os.path.join(FONT_DIR, "arial.ttf")
ARIAL_BOLD = os.path.join(FONT_DIR, "arialbd.ttf")
ARIAL_ITALIC = os.path.join(FONT_DIR, "ariali.ttf")
ARIAL_BOLD_ITALIC = os.path.join(FONT_DIR, "arialbi.ttf")

HAS_UNICODE = all(os.path.isfile(f) for f in [ARIAL_REGULAR, ARIAL_BOLD, ARIAL_ITALIC])
INR = "\u20B9" if HAS_UNICODE else "Rs."


def _fmt_inr(amount, decimals=0):
    if amount is None or amount == 0:
        return f"{INR}0"
    if decimals > 0:
        return f"{INR}{amount:,.{decimals}f}"
    return f"{INR}{amount:,.0f}"


class AccuDesignAuthenticPDF(FPDF):
    """Generates the EXACT layout shown in Image 3 for Accu Design."""

    def __init__(self):
        super().__init__()
        self._font_family = "Helvetica"
        
        # Load Arial Unicode to support Rupee symbol properly
        if HAS_UNICODE:
            try:
                self.add_font("ArialUni", "", ARIAL_REGULAR, uni=True)
                self.add_font("ArialUni", "B", ARIAL_BOLD, uni=True)
                self.add_font("ArialUni", "I", ARIAL_ITALIC, uni=True)
                self._font_family = "ArialUni"
            except Exception:
                pass

    def _set_font(self, style="", size=10):
        self.set_font(self._font_family, style, size)

    def header(self):
        # Top-center title "ACCU DESIGN"
        self._set_font("B", 18)
        self.set_y(15)
        self.cell(0, 7, "ACCU DESIGN", align="C", ln=True)
        
        # Tagline below it
        self._set_font("I", 9)
        self.set_text_color(50, 50, 50)
        self.cell(0, 5, "Accuracy is all that matters...", align="C", ln=True)
        self.set_text_color(0, 0, 0)

        # Place the LOGO on the top right
        if os.path.isfile(LOGO_PATH):
            try:
                # Based on Image 3, logo is perfectly positioned at top right
                # Page width is 210. Margin is 10.
                self.image(LOGO_PATH, x=155, y=5, w=38)
            except Exception:
                pass

        # Draw the double separator line (=============)
        self.ln(2)
        y = self.get_y()
        self.set_line_width(0.4)
        self.set_draw_color(0, 0, 0)
        self.line(10, y, 200, y)
        self.line(10, y + 1.2, 200, y + 1.2)
        
        self.set_y(y + 3)

    def footer(self):
        self.set_y(-30)
        # Double separator line
        y = self.get_y()
        self.set_line_width(0.3)
        self.line(10, y, 200, y)
        self.line(10, y + 1.0, 200, y + 1.0)
        
        self.set_y(y + 2)
        self._set_font("B", 7)
        self.cell(0, 4, "GSTIN: 27ADXPD2924L1Z3", ln=True)
        self._set_font("", 7)
        self.cell(0, 4, "Workshop Address: S.No. 30/15, Unity Industrial Estate, Saidham Road, Dhyari, Pune - 411041", ln=True)
        self.cell(0, 4, "Email ID: projects@accudesign.in  |  Website: www.accudesign.in  |  Generated by ACCU AI", ln=True)


# ══════════════════════════════════════════════════════════════════════════════
# Authentic Generator Function
# ══════════════════════════════════════════════════════════════════════════════

def generate_quote_pdf(
    quote_data: dict,
    quote_number: str = "",
    client_name: str = "",
    client_company: str = "",
    source_filename: str = "",
    parts: list = None,
    screenshot_b64: str = None,
) -> str:
    pdf = AccuDesignAuthenticPDF()
    pdf.set_auto_page_break(auto=True, margin=35)
    pdf.add_page()
    now = datetime.now()

    # ── "Quotation" title center ─────────────────────────────────────────────
    pdf._set_font("B", 11)
    pdf.cell(0, 8, "Quotation", align="C", ln=True)
    pdf.ln(2)

    # ── Date and Quotation Number (Stacked Left) ────────────────────────────
    pdf._set_font("", 9)
    pdf.cell(0, 5, f"Date: {now.strftime('%d/%m/%Y')}", ln=True)
    pdf.cell(0, 5, f"Quotation No: {quote_number}", ln=True)
    pdf.ln(4)

    # ── Client Address Block ─────────────────────────────────────────────────
    pdf._set_font("B", 9)
    pdf.cell(0, 5, "To,", ln=True)
    if client_company:
        pdf.cell(0, 5, client_company, ln=True)
    
    # Optional Source File info
    if source_filename:
        pdf._set_font("I", 8)
        pdf.cell(0, 5, f"Subject: {source_filename}", ln=True)

    pdf.ln(2)
    pdf._set_font("B", 9)
    name_display = f"Mr. {client_name}" if client_name else "Purchasing Manager"
    pdf.cell(0, 5, f"Kindly Attention: {name_display}", ln=True)
    pdf.ln(3)

    # ── Subject Line ─────────────────────────────────────────────────────────
    pdf._set_font("", 9)
    part_name_subject = source_filename.replace('.pdf','').replace('.step','') if source_filename else "parts"
    subj_text = f"We are hereby pleased to share with you the best Techno - commercial offer for the\n{part_name_subject} for your perusal."
    pdf.multi_cell(0, 5, subj_text)
    pdf.ln(6)

    # ── PARTS TABLE ──────────────────────────────────────────────────────────
    # New columns requested: Sr. no. | Description of Supplies/Services | Image | Unit | QTY | Cost
    col_w = [12, 100, 30, 14, 12, 22]
    total_w = sum(col_w) # 190

    headers = ["Sr. no.", "Description of Supplies/Services", "Image", "Unit", "QTY", "Cost"]

    pdf._set_font("B", 7)
    # Lighter shade of logo's blue colour instead of Yellow
    pdf.set_fill_color(225, 240, 255)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.2)

    # Calculate max height for headers
    header_h = 8
    start_x = pdf.get_x()
    start_y = pdf.get_y()
    
    # Draw header cells
    for i, h in enumerate(headers):
        pdf.set_xy(start_x + sum(col_w[:i]), start_y)
        # To handle newlines in headers cleanly, we draw a multi_cell box
        pdf.multi_cell(col_w[i], header_h/2 if '\n' in h else header_h, h, border=1, align="C", fill=True)
        # reset x/y happens automatically but we override
    
    pdf.set_y(start_y + header_h)

    total_a = 0.0
    items_count = 0

    pdf._set_font("", 6.5)
    pdf.set_fill_color(255, 255, 255) # White for body

    def draw_row(idx_str, desc, unit, qty, cost_val, img_path=None):
        h = 24 # Taller row to accommodate 4 lines of description and image
        x = pdf.get_x()
        y = pdf.get_y()
        
        # Check page break
        if y + h > 260:
            pdf.add_page()
            y = pdf.get_y()

        row_data = [
            str(idx_str),
            str(desc),
            "", # for image
            str(unit),
            str(qty),
            cost_val
        ]
        
        for i, val in enumerate(row_data):
            pdf.set_xy(x + sum(col_w[:i]), y)
            align = "C" if i in [0, 2, 3, 4, 5] else "L"
            
            if i == 2:
                if img_path:
                    pdf.cell(col_w[i], h, "", border=1) # Draw empty cell with border
                    # Try to place the image
                    try:
                        img_size = min(col_w[i] - 4, h - 2)
                        pdf.image(img_path, 
                                 x=x + sum(col_w[:i]) + (col_w[i] - img_size)/2, 
                                 y=y + (h - img_size)/2, 
                                 w=img_size, h=img_size)
                    except Exception as e:
                        pdf.set_xy(x + sum(col_w[:i]), y)
                        pdf.cell(col_w[i], h, "Image Error", border=0, align="C")
                else:
                    pdf.cell(col_w[i], h, "", border=1) # Outer border
                    pdf.set_xy(x + sum(col_w[:i]), y + (h - 8) / 2) # Vertically center
                    pdf._set_font("I", 7)
                    pdf.set_text_color(130, 130, 130) # Subtle gray text
                    pdf.multi_cell(col_w[i], 4, "2D Drawing\nProvided", border=0, align="C")
                    pdf.set_text_color(0, 0, 0) # Reset color
                    pdf._set_font("", 6.5) # Reset font
            elif i == 1:
                # Manual multi-cell wrap for Description inside bordered cell
                pdf.cell(col_w[i], h, "", border=1) # Outer border
                pdf.set_xy(x + sum(col_w[:i]) + 2, y + 2) # small padding
                pdf.multi_cell(col_w[i] - 4, 4.5, val, border=0, align="L")
            else:
                pdf.cell(col_w[i], h, val, border=1, align=align)
        
        pdf.set_y(y + h)

    # Prepare screenshot if it exists
    tmp_img_path = None
    if screenshot_b64:
        try:
            pad = len(screenshot_b64) % 4
            b64_clean = screenshot_b64
            if pad: b64_clean += '=' * (4 - pad)
            b64_clean = b64_clean.replace('data:image/png;base64,', '')
            img_bytes = base64.b64decode(b64_clean)
            
            fd, tmp_img_path = tempfile.mkstemp(suffix=".png")
            with open(fd, 'wb') as f:
                f.write(img_bytes)
        except Exception as e:
            print("Failed to decode screenshot:", e)
            tmp_img_path = None

    hsn_code = quote_data.get("hsn_code", "84669310")

    # ── SINGLE SOURCE OF TRUTH: always read these from quote_data ────────────
    # order_total  = pre-tax total  (unit_price_discounted × qty)
    # sgst         = order_total × 9%   (already computed in costing.py)
    # cgst         = order_total × 9%   (already computed in costing.py)
    # grand_total  = order_total + sgst + cgst  ← THE ONLY FINAL AMOUNT
    #
    # We NEVER recalculate tax here. We NEVER multiply unit_price × qty again.
    # We read the pre-computed values exactly as returned by compute_quote().

    if parts and len(parts) > 0:
        for idx, part in enumerate(parts, 1):
            # cost_inr must be the already-computed order_total for that part
            # (unit_price_discounted × qty) — NOT unit_price alone
            rcost = part.get("order_total", part.get("cost_inr", 0))
            mat   = part.get("material_short", part.get("material", "-"))
            tol   = part.get("tolerance", "Standard")
            part_no = f"0{idx}"
            desc_str = (
                f"Manufacturing of {mat} Parts as per sample provided.\n"
                f"Raw material: {mat}\n"
                f"Tolerance: {tol}\n"
                f"Part Number: {part_no}"
            )
            draw_row(
                idx_str=idx,
                desc=desc_str,
                unit="Nos",
                qty=part.get("quantity", 1),
                cost_val=_fmt_inr(rcost),
                img_path=tmp_img_path if idx == 1 else None,
            )
            items_count = idx
    else:
        # Single-part quote — order_total is the pre-tax subtotal
        rcost   = quote_data.get("order_total", 0)   # ← pre-tax order total
        mat     = quote_data.get("material", "-")
        tol     = quote_data.get("tolerance", "Standard")
        part_no = "01"
        desc_str = (
            f"Manufacturing of {mat} Parts as per sample provided.\n"
            f"Raw material: {mat}\n"
            f"Tolerance: {tol}\n"
            f"Part Number: {part_no}"
        )
        draw_row(
            "1",
            desc=desc_str,
            unit="Nos",
            qty=quote_data.get("quantity", 1),
            cost_val=_fmt_inr(rcost),          # ← shows order_total in cost column
            img_path=tmp_img_path,
        )
        items_count = 1

    # ── TOTALS BLOCK ─────────────────────────────────────────────────────────
    # Layout: Sr# | Label (merged middle cols) | Cost
    # Rows: Order Subtotal | SGST (9%) | CGST (9%) | Grand Total | Amount in Words
    # NO "Total A", NO "Total B", NO "Taxation C" — removed per requirement.

    label_w = sum(col_w[1:-1])
    cost_w  = col_w[-1]

    def draw_appended_row(desc_label, cost_val, color=None, is_words=False, bold=False):
        nonlocal items_count
        items_count += 1
        h   = 6
        x   = pdf.get_x()
        y   = pdf.get_y()
        fill = bool(color)
        if color:
            pdf.set_fill_color(*color)

        pdf.set_xy(x, y)
        pdf.cell(col_w[0], h, str(items_count), border=1, align="C", fill=fill)

        if is_words:
            pdf.set_xy(x + col_w[0], y)
            pdf._set_font("B", 7)
            pdf.cell(label_w + cost_w, h, desc_label, border=1, align="L", fill=fill)
        else:
            pdf.set_xy(x + col_w[0], y)
            pdf._set_font("B" if bold else "", 7)
            pdf.cell(label_w, h, desc_label, border=1, align="C", fill=fill)
            pdf.set_xy(x + col_w[0] + label_w, y)
            pdf._set_font("B" if bold else "", 7)
            pdf.cell(cost_w, h, cost_val, border=1, align="C", fill=fill)

        pdf._set_font("", 6.5)
        pdf.set_y(y + h)

    # Read pre-computed values — NEVER recalculate
    order_total = quote_data.get("order_total", 0)
    sgst        = quote_data.get("sgst",        round(order_total * 0.09, 2))
    cgst        = quote_data.get("cgst",        round(order_total * 0.09, 2))
    grand_total = quote_data.get("grand_total", round(order_total + sgst + cgst, 2))

    # Row 2: Order Subtotal (pre-tax)
    draw_appended_row("Order Subtotal (Pre-Tax)", _fmt_inr(order_total))

    # Row 3: SGST 9%
    draw_appended_row("SGST @ 9%", _fmt_inr(sgst))

    # Row 4: CGST 9%
    draw_appended_row("CGST @ 9%", _fmt_inr(cgst))

    # Row 5: Grand Total — bold + light blue highlight
    draw_appended_row(
        "Grand Total (Incl. GST)",
        _fmt_inr(grand_total),
        color=(210, 235, 255),
        bold=True,
    )

    # Row 6: Amount in Words — same light blue
    words = amount_in_words(int(round(grand_total)))
    draw_appended_row(
        f"Amount in Words: {words}",
        "",
        color=(215, 240, 255),
        is_words=True,
    )

    pdf.ln(10)

    # ── TECHNICAL DATA TABLE ────────────────────────────────────────────────
    pdf._set_font("B", 8)
    pdf.cell(0, 5, "Technical Parameters:", ln=True)
    
    tech_col_w = [12, 20, 45, 23, 90]
    tech_headers = ["Sr. no.", "PART NO.", "DIMENSIONS", "Weight (kg)", "MANUFACTURING PROCESS"]
    pdf.set_fill_color(225, 240, 255) # Light blue
    pdf.set_draw_color(0, 0, 0)
    
    pdf._set_font("B", 7)
    for i, h_text in enumerate(tech_headers):
        pdf.cell(tech_col_w[i], 6, h_text, border=1, align="C", fill=True)
    pdf.ln(6)
    
    pdf._set_font("", 7)
    if parts and len(parts) > 0:
        for idx, part in enumerate(parts, 1):
            part_num = f"RF{quote_number[-4:]}-{idx:02d}"
            dims = part.get("dimensions_str", "-")[:40]
            wt = f"{part.get('weight_kg', 0):.3f}"
            proc = part.get("manufacturing_processes_str", "-")[:100]
            
            pdf.cell(tech_col_w[0], 6, str(idx), border=1, align="C")
            pdf.cell(tech_col_w[1], 6, str(part_num), border=1, align="C")
            pdf.cell(tech_col_w[2], 6, str(dims), border=1, align="C")
            pdf.cell(tech_col_w[3], 6, str(wt), border=1, align="C")
            pdf.cell(tech_col_w[4], 6, str(proc), border=1, align="L")
            pdf.ln(6)
    else:
        part_num = "01"
        bb = quote_data.get("bounding_box", {})
        if "boundingBox" in quote_data: # handle diff schema structures cleanly
            bb = quote_data["boundingBox"]
        dims = f"{bb.get('sizeX', 0):.0f}x{bb.get('sizeY', 0):.0f}x{bb.get('sizeZ', 0):.0f}" if bb else "CAD Data"
        wt = f"{quote_data.get('mass_kg', 0):.3f}"
        proc = quote_data.get("process", "CNC Machining")
        
        pdf.cell(tech_col_w[0], 6, "1", border=1, align="C")
        pdf.cell(tech_col_w[1], 6, part_num, border=1, align="C")
        pdf.cell(tech_col_w[2], 6, dims, border=1, align="C")
        pdf.cell(tech_col_w[3], 6, wt, border=1, align="C")
        pdf.cell(tech_col_w[4], 6, proc, border=1, align="L")
        pdf.ln(6)

    pdf.ln(10)

    # Prevent footer overlap: if Y is deep on the page, add page before T&C block
    if pdf.get_y() > 210:
        pdf.add_page()

    # ── TERMS & CONDITIONS ───────────────────────────────────────────────────
    pdf._set_font("B", 8)
    pdf.cell(0, 5, "Terms & Conditions:", ln=True)
    pdf._set_font("", 8)

    terms = [
        "Delivery Time within 3-4 weeks, Inclusive of Transportation.",
        "70% Advance and remaining payment successful quality acceptance by client.",
        "Validity of the above quotation for 15 days.",
        "All disputes are subject to Pune jurisdiction only.",
    ]
    for i, t in enumerate(terms, 1):
        pdf.cell(0, 4.5, f"{i}. {t}", ln=True)

    pdf.ln(8)

    # ── SIGNATURE ────────────────────────────────────────────────────────────
    if pdf.get_y() > 240:
        pdf.add_page()
        
    pdf._set_font("", 9)
    pdf.cell(0, 5, "Yours Faithfully,", ln=True)
    pdf.ln(4)
    
    stamp_placed = False
    for path in [os.path.join(ASSETS_DIR, "stamp.png"), os.path.join(ASSETS_DIR, "stamp.jpg"), os.path.join(ASSETS_DIR, "stamp.jpeg")]:
        if os.path.isfile(path):
            try:
                pdf.image(path, x=10, y=pdf.get_y(), w=60)
                pdf.set_y(pdf.get_y() + 25)
                stamp_placed = True
                break
            except Exception:
                pass
                
    if not stamp_placed:
        pdf._set_font("B", 9)
        pdf.cell(0, 5, "For ACCU DESIGN", ln=True)
        pdf.ln(8)
        
    # ── Save & return ─────────────────────────────────────────────────────────
    # Returns (tmp_path, suggested_filename).
    # Caller must use suggested_filename for the download — NOT a random timestamp.
    # Quote number e.g. "AD/XX/1903/25-26/AbCd" → "AD_XX_1903_25-26_AbCd"
    safe_qnum = quote_number.replace("/", "_").strip()
    suggested_filename = f"ACCUDESIGN_QUOTE_{safe_qnum}.pdf"

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)

        # Cleanup temporary screenshot image if it was created
        if tmp_img_path and os.path.exists(tmp_img_path):
            try:
                os.remove(tmp_img_path)
            except Exception:
                pass

        return tmp.name, suggested_filename


# ══════════════════════════════════════════════════════════════════════════════
# BOM Assembly Quote PDF — Portrait A4 Layout (Industry Standard)
# ══════════════════════════════════════════════════════════════════════════════

def generate_bom_quote_pdf(
    parts: list,
    quote_number: str = "",
    client_name: str = "",
    client_company: str = "",
    hsn_code: str = "84669310",
    source_filename: str = "",
    profit_margin_pct: float = 22.0,
) -> str:
    """Generate a clean, professional BOM assembly quotation PDF in Portrait A4."""

    pdf = AccuDesignAuthenticPDF()
    pdf.set_auto_page_break(auto=True, margin=35)
    pdf.add_page()
    now = datetime.now()

    # ── "Quotation" title center ─────────────────────────────────────────────
    pdf._set_font("B", 11)
    pdf.cell(0, 8, "Quotation", align="C", ln=True)
    pdf.ln(2)

    # ── Date and Quotation Number ────────────────────────────────────────────
    pdf._set_font("", 9)
    # Start X pos
    x_left = pdf.get_x()
    pdf.cell(40, 5, "Date", ln=False)
    pdf.cell(50, 5, f": {now.strftime('%d/%m/%Y')}", ln=True)

    pdf.cell(40, 5, "Quotation No.", ln=False)
    pdf.cell(50, 5, f": {quote_number}", ln=True)
    pdf.ln(3)

    # ── Client Info ──────────────────────────────────────────────────────────
    pdf._set_font("B", 8)
    pdf.cell(0, 5, "To,", ln=True)
    if client_company:
        pdf.cell(0, 5, client_company, ln=True)
    
    if source_filename:
        pdf._set_font("I", 8)
        pdf.cell(0, 5, f"Subject: {source_filename}", ln=True)

    pdf.ln(2)
    pdf._set_font("B", 9)
    name_display = f"Mr. {client_name}" if client_name else "Purchasing Manager"
    pdf.cell(0, 5, f"Kindly Attention: {name_display}", ln=True)
    pdf.ln(3)

    # ── Subject Line ─────────────────────────────────────────────────────────
    pdf._set_font("", 9)
    part_label = source_filename.replace('.pdf', '').replace('.step', '') if source_filename else "parts"
    subj_text = f"We are hereby pleased to share with you the best Techno - commercial offer for the\n{part_label} for your perusal."
    pdf.multi_cell(0, 5, subj_text)
    pdf.ln(6)

    # ═══════════════════════ EXACT INVOICE TABLE BOM ═════════════════════════
    # Columns: Sr#, DESCRIPTION, DIMENSIONS, CATEGORY, PART NO., MATERIAL, QTY., Weight(kg), MFG PROCESS, Cost
    # DESCRIPTION and MATERIAL widened; rows use multi_cell so text wraps instead of being cut off
    COL_W = [7, 30, 20, 14, 12, 22, 9, 13, 42, 21]  # sum = 190
    COL_H = ["Sr#", "DESCRIPTION", "DIMENSIONS", "CATEGORY", "PART\nNO.", "MATERIAL", "QTY.", "Weight\n(kg)", "MANUFACTURING\nPROCESS", "Cost"]
    HDR_H = 8
    ROW_H = 8   # minimum row height; multi_cell rows auto-expand
    
    def _draw_table_header():
        pdf._set_font("B", 6)
        pdf.set_fill_color(240, 245, 255) # Light blueish header fill
        pdf.set_draw_color(0, 0, 0)
        pdf.set_line_width(0.2)
        
        y = pdf.get_y()
        for i, h in enumerate(COL_H):
            pdf.set_xy(10 + sum(COL_W[:i]), y)
            # Use multi_cell for headers with newlines
            if "\n" in h:
                x_start = pdf.get_x()
                pdf.multi_cell(COL_W[i], HDR_H/2, h, border=1, align="C", fill=True)
                pdf.set_xy(x_start + COL_W[i], y)
            else:
                pdf.cell(COL_W[i], HDR_H, h, border=1, align="C", fill=True)
        
        pdf.set_y(y + HDR_H)

    _draw_table_header()

    machined_total = 0.0

    pdf._set_font("B", 6)
    
    # Yellow highlighted "Assembly" row just like the image
    part_label = source_filename.replace('.pdf', '').replace('.step', '') if source_filename else "ASSEMBLY"
    y = pdf.get_y()
    pdf.cell(COL_W[0], 6, "A", border=1, align="C")
    pdf.cell(COL_W[1], 6, str(part_label)[:25].upper(), border=1, align="C")
    pdf.cell(COL_W[2], 6, "", border=1, align="C")
    pdf.set_fill_color(255, 255, 150)
    pdf.cell(COL_W[3], 6, "Assembly", border=1, align="C", fill=True)
    pdf.cell(COL_W[4], 6, "", border=1, align="C")
    pdf.cell(COL_W[5], 6, "", border=1, align="C")
    pdf.cell(COL_W[6], 6, "1 SET", border=1, align="C")
    pdf.cell(COL_W[7], 6, "", border=1, align="C")
    pdf.cell(COL_W[8], 6, "", border=1, align="C")
    pdf.cell(COL_W[9], 6, "", border=1, align="C")
    pdf.ln(6)
    
    pdf._set_font("", 6)

    for idx, p in enumerate(parts):
        is_buyout  = bool(p.get('isBuyout', False))
        qty        = int(p.get('qty', p.get('quantity', 1)))

        # ── CRITICAL: row_amount is the already-computed pre-tax order total ──
        # It must come from order_total (unit_price_discounted × qty already done
        # in costing.py).  Do NOT multiply unit_price × qty here — that causes
        # a 4–5× inflation bug when unit_price is already the per-unit rate.
        if is_buyout:
            row_amount = 0.0
        else:
            # Prefer order_total (pre-tax total for this part).
            # Fall back to cost_inr, then unit_price_discounted × qty.
            row_amount = float(
                p.get("order_total")
                or p.get("cost_inr")
                or (p.get("unit_price_discounted", p.get("unit_price", 0)) * qty)
                or 0
            )
        
        item_num  = str(p.get('item_number', str(idx + 1).zfill(2)))
        part_name = p.get('name', 'PART').upper()
        dims      = str(p.get('dimensions', '-'))
        material  = str(p.get('material', 'EN-8')).upper()
        weight    = str(p.get('weight_kg', '-'))
        process   = p.get('process', 'Machining')
        cost_str  = "AT ACTUAL" if is_buyout else _fmt_inr(row_amount)
        cost_bold = is_buyout

        # ── Word-wrap splitter ────────────────────────────────────────────────
        # Splits text into lines that fit inside col_width mm.
        # Uses FPDF's real get_string_width — 100% accurate, no estimates.
        def _split_lines(text, col_width, font_size=6):
            pdf._set_font("", font_size)
            usable = col_width - 2.0   # 1 mm padding each side
            result = []
            for para in text.split('\n'):
                if not para.strip():
                    result.append('')
                    continue
                words = para.split(' ')
                current = ''
                for word in words:
                    test = (current + ' ' + word).strip()
                    if pdf.get_string_width(test) <= usable:
                        current = test
                    else:
                        if current:
                            result.append(current)
                        # If single word wider than column, keep it anyway
                        current = word
                if current:
                    result.append(current)
            return result if result else ['']

        LINE_H = 4.0   # mm per text line
        PAD_T  = 1.5   # top padding mm

        # Pre-split all wrapping columns to know exact line counts
        lines_desc = _split_lines(part_name, COL_W[1])
        lines_mat  = _split_lines(material,  COL_W[5])
        lines_proc = _split_lines(process,   COL_W[8])

        # Row height = tallest column + padding
        row_h = max(
            ROW_H,
            max(len(lines_desc), len(lines_mat), len(lines_proc)) * LINE_H + PAD_T + 1.5
        )

        # Page-break check with actual row height
        if pdf.get_y() + row_h > 260:
            pdf.add_page()
            _draw_table_header()
            pdf._set_font("", 6)

        y_start = pdf.get_y()
        x_start = 10

        # ── Draw a simple fixed-height cell (no wrapping needed) ─────────────
        def _cell(col_idx, text, align="C", bold=False):
            pdf.set_xy(x_start + sum(COL_W[:col_idx]), y_start)
            pdf._set_font("B" if bold else "", 6)
            pdf.cell(COL_W[col_idx], row_h, text, border=1, align=align)
            # Restore — cell() moves x forward but not y; safe.

        # ── Draw a wrapping cell using only cell() — NO multi_cell ───────────
        # Draws the border rect, then places each pre-split line individually.
        # Cursor is ALWAYS restored to (cx+cw, y_start) after drawing.
        def _wrap_cell(col_idx, lines, bold=False):
            cx = x_start + sum(COL_W[:col_idx])
            cw = COL_W[col_idx]
            # Border rectangle at full row height
            pdf.set_line_width(0.2)
            pdf.rect(cx, y_start, cw, row_h)
            # Draw each line as a plain cell() at precise Y
            for i, line in enumerate(lines):
                ly = y_start + PAD_T + i * LINE_H
                pdf.set_xy(cx + 1, ly)
                pdf._set_font("B" if bold else "", 6)
                pdf.cell(cw - 2, LINE_H, line, border=0, align="L")
            # Always restore cursor — this is the key fix
            pdf.set_xy(cx + cw, y_start)

        # ── Render all 10 columns ─────────────────────────────────────────────
        _cell(0, str(idx + 1))
        _wrap_cell(1, lines_desc)                      # DESCRIPTION
        _cell(2, dims)
        _cell(3, "Buyout" if is_buyout else "Part")
        _cell(4, item_num)
        _wrap_cell(5, lines_mat)                       # MATERIAL
        _cell(6, str(qty))
        _cell(7, weight)
        _wrap_cell(8, lines_proc)                      # MANUFACTURING PROCESS
        _cell(9, cost_str, align="C", bold=cost_bold)  # AT ACTUAL (bold) or cost

        # Advance Y by exactly row_h — guaranteed no overlap with next row
        pdf.set_y(y_start + row_h)

        if not is_buyout:
            machined_total += row_amount

    # ═══════════════════════ TOTALS BLOCK ════════════════════════════════════
    # NO "Total A", NO "Total B", NO "Taxation C" — removed per requirement.
    # All values read from pre-computed costing.py output — never recalculated.
    if pdf.get_y() + 50 > 260:
        pdf.add_page()
    
    pdf.ln(4)
    
    # Calculate starting Sr# index (after all part rows)
    start_idx = len(parts) + 1
    
    w_left  = COL_W[0]
    w_mid   = sum(COL_W[1:-1])
    w_right = COL_W[-1]

    def total_row(num, text, amount_str, bold=False, color=None):
        fill = bool(color)
        if color:
            pdf.set_fill_color(*color)
        pdf._set_font("B" if bold else "", 7)
        pdf.cell(w_left,  6, str(num),       border=1, align="C",              fill=fill)
        pdf.cell(w_mid,   6, text,            border=1, align="C",              fill=fill)
        pdf.cell(w_right, 6, amount_str,      border=1, align="R",              fill=fill)
        pdf.ln(6)

    # ── Aggregate pre-tax total across all non-buyout parts ──────────────────
    # Each part's order_total is already unit_price_discounted × qty from costing.py
    order_subtotal = sum(
        float(p.get("order_total") or p.get("cost_inr") or 0)
        for p in parts
        if not p.get("isBuyout", False)
    )

    # ── Read GST from first quoted part (rates are always 9%+9%) ─────────────
    # If parts carry their own sgst/cgst fields, sum them; otherwise compute.
    sgst_total = sum(float(p.get("sgst", 0)) for p in parts if not p.get("isBuyout", False))
    cgst_total = sum(float(p.get("cgst", 0)) for p in parts if not p.get("isBuyout", False))

    # Fallback: if parts don't carry pre-computed GST, compute from subtotal
    if sgst_total == 0:
        sgst_total = round(order_subtotal * 0.09, 2)
    if cgst_total == 0:
        cgst_total = round(order_subtotal * 0.09, 2)

    grand_total_bom = round(order_subtotal + sgst_total + cgst_total, 2)

    # Row: Order Subtotal (pre-tax)
    total_row(start_idx,     "Order Subtotal (Pre-Tax)",  _fmt_inr(order_subtotal))
    # Row: SGST
    total_row(start_idx + 1, "SGST @ 9%",                _fmt_inr(sgst_total))
    # Row: CGST
    total_row(start_idx + 2, "CGST @ 9%",                _fmt_inr(cgst_total))
    # Row: Grand Total — bold + highlight
    total_row(start_idx + 3, "Grand Total (Incl. GST)",  _fmt_inr(grand_total_bom),
              bold=True, color=(210, 235, 255))

    # Row: Amount in Words — amount_in_words() already ends with "Rupees Only"
    # do NOT append anything extra — that caused "Rupees Only Rupees Only" bug
    pdf.set_fill_color(215, 240, 255)
    pdf._set_font("B", 7)
    rounded_bom = int(round(grand_total_bom))
    words_str = "Amount in Words: " + amount_in_words(rounded_bom)
    pdf.cell(w_left,          7, str(start_idx + 4), border=1, align="C", fill=True)
    pdf.cell(w_mid + w_right, 7, words_str,           border=1, align="L", fill=True)
    pdf.ln(7)

    # ═══════════════════════ TERMS & CONDITIONS ══════════════════════════════
    pdf.ln(8)
    if pdf.get_y() > 250:
        pdf.add_page()

    pdf._set_font("B", 9)
    pdf.cell(0, 5, "Terms & Conditions:", ln=True)
    pdf._set_font("", 8)

    # GST point REMOVED (GST is already shown in the table above).
    # Delivery updated to "3-4 weeks".
    terms = [
        "Delivery Time within 3-4 weeks, Inclusive of Transportation.",
        "70% Advance and remaining payment successful quality acceptance by client.",
        "Validity of the above quotation for 15 days.",
        "All disputes are subject to Pune jurisdiction only.",
    ]
    for i, t in enumerate(terms, 1):
        pdf.cell(0, 4.5, f"{i}. {t}", ln=True)

    pdf.ln(8)
    if pdf.get_y() > 240:
        pdf.add_page()

    # ── SIGNATURE ────────────────────────────────────────────────────────────
    pdf._set_font("", 9)
    pdf.cell(0, 5, "Yours Faithfully,", ln=True)
    pdf.ln(4)

    stamp_placed = False
    for path in [
        os.path.join(ASSETS_DIR, "stamp.png"),
        os.path.join(ASSETS_DIR, "stamp.jpg"),
        os.path.join(ASSETS_DIR, "stamp.jpeg"),
    ]:
        if os.path.isfile(path):
            try:
                pdf.image(path, x=10, y=pdf.get_y(), w=60)
                pdf.set_y(pdf.get_y() + 25)
                stamp_placed = True
                break
            except Exception:
                pass

    if not stamp_placed:
        pdf._set_font("B", 9)
        pdf.cell(0, 5, "For ACCU DESIGN", ln=True)
        pdf.ln(8)

    # ── Save & return ─────────────────────────────────────────────────────────
    # Returns (tmp_path, suggested_filename) so the caller can set the download
    # name as  ACCUDESIGN_BOM_QUOTE_{quote_number}.pdf  — NOT a random timestamp.
    # Quote number e.g. "AD/BOM/4582" → "AD_BOM_4582"
    safe_qnum = quote_number.replace("/", "_").strip()
    suggested_filename = f"ACCUDESIGN_BOM_QUOTE_{safe_qnum}.pdf"

    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        return tmp.name, suggested_filename