"""
Authentic ACCU DESIGN Quotation Generator

Matches the exact layout from the provided Image 3 reference.
  - Symmetrical, proper positioning, no off-center boxes
  - Header with Logo top-right
  - Stacked Date/Quote No on the left
  - Table: Sr#, DESCRIPTION, DIMENSIONS, CATEGORY, PART NO, MATERIAL, QTY, Weight(kg), MANUFACTURING PROCESS, Cost
  - Totals: Appended cleanly to the bottom of the table
  - Grand total and Amount in Words highlighted in lime-green
  - Footer with double line separator
  - Full Unicode support for exact formatting (₹ symbol)
"""

import tempfile
import base64
import os
from fpdf import FPDF
from datetime import datetime

try:
    from services.quote_number import amount_in_words
except ImportError:
    from quote_number import amount_in_words

# ── Resolve paths ────────────────────────────────────────────────────────────
BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS_DIR = os.path.join(BACKEND_DIR, "assets")
LOGO_PATH = os.path.join(ASSETS_DIR, "logo.png")

# ── Windows font paths (for Unicode ₹ support) ──────────────────────────────
FONT_DIR = r"C:\Windows\Fonts"
ARIAL_REGULAR = os.path.join(FONT_DIR, "arial.ttf")
ARIAL_BOLD = os.path.join(FONT_DIR, "arialbd.ttf")
ARIAL_ITALIC = os.path.join(FONT_DIR, "ariali.ttf")
ARIAL_BOLD_ITALIC = os.path.join(FONT_DIR, "arialbi.ttf")

HAS_UNICODE = all(os.path.isfile(f) for f in [ARIAL_REGULAR, ARIAL_BOLD, ARIAL_ITALIC])
INR = "\u20B9" if HAS_UNICODE else "Rs."


def _fmt_inr(amount, decimals=0):
    if amount is None or amount == 0:
        return f"{INR}0"
    if decimals > 0:
        return f"{INR}{amount:,.{decimals}f}"
    return f"{INR}{amount:,.0f}"


class AccuDesignAuthenticPDF(FPDF):
    """Generates the EXACT layout shown in Image 3 for Accu Design."""

    def __init__(self):
        super().__init__()
        self._font_family = "Helvetica"
        
        # Load Arial Unicode to support Rupee symbol properly
        if HAS_UNICODE:
            try:
                self.add_font("ArialUni", "", ARIAL_REGULAR, uni=True)
                self.add_font("ArialUni", "B", ARIAL_BOLD, uni=True)
                self.add_font("ArialUni", "I", ARIAL_ITALIC, uni=True)
                self._font_family = "ArialUni"
            except Exception:
                pass

    def _set_font(self, style="", size=10):
        self.set_font(self._font_family, style, size)

    def header(self):
        # Top-center title "ACCU DESIGN"
        self._set_font("B", 18)
        self.set_y(15)
        self.cell(0, 7, "ACCU DESIGN", align="C", ln=True)
        
        # Tagline below it
        self._set_font("I", 9)
        self.set_text_color(50, 50, 50)
        self.cell(0, 5, "Accuracy is all that matters...", align="C", ln=True)
        self.set_text_color(0, 0, 0)

        # Place the LOGO on the top right
        if os.path.isfile(LOGO_PATH):
            try:
                # Based on Image 3, logo is perfectly positioned at top right
                # Page width is 210. Margin is 10.
                self.image(LOGO_PATH, x=155, y=5, w=38)
            except Exception:
                pass

        # Draw the double separator line (=============)
        self.ln(2)
        y = self.get_y()
        self.set_line_width(0.4)
        self.set_draw_color(0, 0, 0)
        self.line(10, y, 200, y)
        self.line(10, y + 1.2, 200, y + 1.2)
        
        self.set_y(y + 3)

    def footer(self):
        self.set_y(-30)
        # Double separator line
        y = self.get_y()
        self.set_line_width(0.3)
        self.line(10, y, 200, y)
        self.line(10, y + 1.0, 200, y + 1.0)
        
        self.set_y(y + 2)
        self._set_font("B", 7)
        self.cell(0, 4, "GSTIN: 27ADXPD2924L1Z3", ln=True)
        self._set_font("", 7)
        self.cell(0, 4, "Workshop Address: S.No. 30/15, Unity Industrial Estate, Saidham Road, Dhyari, Pune - 411041", ln=True)
        self.cell(0, 4, "Email ID: projects@accudesign.in  |  Website: www.accudesign.in  |  Generated by ACCU AI", ln=True)


# ══════════════════════════════════════════════════════════════════════════════
# Authentic Generator Function
# ══════════════════════════════════════════════════════════════════════════════

def generate_quote_pdf(
    quote_data: dict,
    quote_number: str = "",
    client_name: str = "",
    client_company: str = "",
    source_filename: str = "",
    parts: list = None,
    screenshot_b64: str = None,
) -> str:
    pdf = AccuDesignAuthenticPDF()
    pdf.set_auto_page_break(auto=True, margin=35)
    pdf.add_page()
    now = datetime.now()

    # ── "Quotation" title center ─────────────────────────────────────────────
    pdf._set_font("B", 11)
    pdf.cell(0, 8, "Quotation", align="C", ln=True)
    pdf.ln(2)

    # ── Date and Quotation Number (Stacked Left) ────────────────────────────
    pdf._set_font("", 9)
    pdf.cell(0, 5, f"Date: {now.strftime('%d/%m/%Y')}", ln=True)
    pdf.cell(0, 5, f"Quotation No: {quote_number}", ln=True)
    pdf.ln(4)

    # ── Client Address Block ─────────────────────────────────────────────────
    pdf._set_font("B", 9)
    pdf.cell(0, 5, "To,", ln=True)
    if client_company:
        pdf.cell(0, 5, client_company, ln=True)
    
    # Optional Source File info
    if source_filename:
        pdf._set_font("I", 8)
        pdf.cell(0, 5, f"Subject: {source_filename}", ln=True)

    pdf.ln(2)
    pdf._set_font("B", 9)
    name_display = f"Mr. {client_name}" if client_name else "Purchasing Manager"
    pdf.cell(0, 5, f"Kindly Attention: {name_display}", ln=True)
    pdf.ln(3)

    # ── Subject Line ─────────────────────────────────────────────────────────
    pdf._set_font("", 9)
    part_name_subject = source_filename.replace('.pdf','').replace('.step','') if source_filename else "parts"
    subj_text = f"We are hereby pleased to share with you the best Techno - commercial offer for the\n{part_name_subject} for your perusal."
    pdf.multi_cell(0, 5, subj_text)
    pdf.ln(6)

    # ── PARTS TABLE ──────────────────────────────────────────────────────────
    # New columns requested: Sr. no. | Description of Supplies/Services | Image | Unit | QTY | Cost
    col_w = [12, 100, 30, 14, 12, 22]
    total_w = sum(col_w) # 190

    headers = ["Sr. no.", "Description of Supplies/Services", "Image", "Unit", "QTY", "Cost"]

    pdf._set_font("B", 7)
    # Lighter shade of logo's blue colour instead of Yellow
    pdf.set_fill_color(225, 240, 255)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.2)

    # Calculate max height for headers
    header_h = 8
    start_x = pdf.get_x()
    start_y = pdf.get_y()
    
    # Draw header cells
    for i, h in enumerate(headers):
        pdf.set_xy(start_x + sum(col_w[:i]), start_y)
        # To handle newlines in headers cleanly, we draw a multi_cell box
        pdf.multi_cell(col_w[i], header_h/2 if '\n' in h else header_h, h, border=1, align="C", fill=True)
        # reset x/y happens automatically but we override
    
    pdf.set_y(start_y + header_h)

    total_a = 0.0
    items_count = 0

    pdf._set_font("", 6.5)
    pdf.set_fill_color(255, 255, 255) # White for body

    def draw_row(idx_str, desc, unit, qty, cost_val, img_path=None):
        h = 24 # Taller row to accommodate 4 lines of description and image
        x = pdf.get_x()
        y = pdf.get_y()
        
        # Check page break
        if y + h > 260:
            pdf.add_page()
            y = pdf.get_y()

        row_data = [
            str(idx_str),
            str(desc),
            "", # for image
            str(unit),
            str(qty),
            cost_val
        ]
        
        for i, val in enumerate(row_data):
            pdf.set_xy(x + sum(col_w[:i]), y)
            align = "C" if i in [0, 2, 3, 4, 5] else "L"
            
            if i == 2:
                if img_path:
                    pdf.cell(col_w[i], h, "", border=1) # Draw empty cell with border
                    # Try to place the image
                    try:
                        img_size = min(col_w[i] - 4, h - 2)
                        pdf.image(img_path, 
                                 x=x + sum(col_w[:i]) + (col_w[i] - img_size)/2, 
                                 y=y + (h - img_size)/2, 
                                 w=img_size, h=img_size)
                    except Exception as e:
                        pdf.set_xy(x + sum(col_w[:i]), y)
                        pdf.cell(col_w[i], h, "Image Error", border=0, align="C")
                else:
                    pdf.cell(col_w[i], h, "", border=1) # Outer border
                    pdf.set_xy(x + sum(col_w[:i]), y + (h - 8) / 2) # Vertically center
                    pdf._set_font("I", 7)
                    pdf.set_text_color(130, 130, 130) # Subtle gray text
                    pdf.multi_cell(col_w[i], 4, "2D Drawing\nProvided", border=0, align="C")
                    pdf.set_text_color(0, 0, 0) # Reset color
                    pdf._set_font("", 6.5) # Reset font
            elif i == 1:
                # Manual multi-cell wrap for Description inside bordered cell
                pdf.cell(col_w[i], h, "", border=1) # Outer border
                pdf.set_xy(x + sum(col_w[:i]) + 2, y + 2) # small padding
                pdf.multi_cell(col_w[i] - 4, 4.5, val, border=0, align="L")
            else:
                pdf.cell(col_w[i], h, val, border=1, align=align)
        
        pdf.set_y(y + h)

    # Prepare screenshot if it exists
    tmp_img_path = None
    if screenshot_b64:
        try:
            pad = len(screenshot_b64) % 4
            b64_clean = screenshot_b64
            if pad: b64_clean += '=' * (4 - pad)
            b64_clean = b64_clean.replace('data:image/png;base64,', '')
            img_bytes = base64.b64decode(b64_clean)
            
            fd, tmp_img_path = tempfile.mkstemp(suffix=".png")
            with open(fd, 'wb') as f:
                f.write(img_bytes)
        except Exception as e:
            print("Failed to decode screenshot:", e)
            tmp_img_path = None

    hsn_code = quote_data.get("hsn_code", "84669310")

    if parts and len(parts) > 0:
        for idx, part in enumerate(parts, 1):
            rcost = part.get("cost_inr", 0)
            total_a += rcost
            mat = part.get("material_short", "-")
            tol = part.get("tolerance", "Standard")
            part_no = f"RF{quote_number[-4:]}-{idx:02d}"
            desc_str = f"Manufacturing of {mat} Parts as per sample provided.\nRaw material: {mat}\nTolerance: {tol}\nPart Number: {part_no}"
            
            draw_row(
                idx_str=idx,
                desc=desc_str,
                unit="Nos",
                qty=part.get("quantity", 1),
                cost_val=_fmt_inr(rcost),
                img_path=tmp_img_path if idx == 1 else None
            )
            items_count = idx
    else:
        rcost = quote_data.get("order_total", 0)
        total_a = rcost
        mat = quote_data.get("material", "-")
        tol = quote_data.get("tolerance", "Standard")
        part_no = "01"
        desc_str = f"Manufacturing of {mat} Parts as per sample provided.\nRaw material: {mat}\nTolerance: {tol}\nPart Number: {part_no}"
        
        draw_row(
            "1",
            desc=desc_str,
            unit="Nos",
            qty=quote_data.get("quantity", 1),
            cost_val=_fmt_inr(rcost),
            img_path=tmp_img_path
        )
        items_count = 1

    # ── TOTALS APPENDED ROWS ─────────────────────────────────────────────────
    # In Image 3, the totals are perfectly aligned below the table,
    # where the Sr# column increments, the middle columns merge into a label, and Cost is filled.
    label_w = sum(col_w[1:-1]) # Everything between Sr# and Cost
    cost_w = col_w[-1]

    def draw_appended_row(desc_label, cost_val, color=None, is_words=False):
        nonlocal items_count
        items_count += 1
        
        h = 6
        x = pdf.get_x()
        y = pdf.get_y()

        fill = False
        if color:
            pdf.set_fill_color(*color)
            fill = True

        # Sr# Col
        pdf.set_xy(x, y)
        pdf.cell(col_w[0], h, str(items_count), border=1, align="C", fill=fill)
        
        # Label & Cost
        if is_words:
            # Spans label_w AND cost_w
            pdf.set_xy(x + col_w[0], y)
            pdf._set_font("B", 7)
            pdf.cell(label_w + cost_w, h, desc_label, border=1, align="L", fill=fill)
        else:
            pdf.set_xy(x + col_w[0], y)
            pdf.cell(label_w, h, desc_label, border=1, align="C", fill=fill)
            pdf.set_xy(x + col_w[0] + label_w, y)
            pdf._set_font("B" if "TOTAL" in desc_label else "", 7)
            pdf.cell(cost_w, h, cost_val, border=1, align="C", fill=fill)

        pdf._set_font("", 6.5) # reset
        pdf.set_y(y + h)

    # 1. Total A
    draw_appended_row("TOTAL A", _fmt_inr(total_a))
    
    # 2. Additions (Hide if 0)
    surf_cost = quote_data.get("surface_treatment_cost", 0)
    log_cost = quote_data.get("logistics_cost", 0)
    eng_cost = quote_data.get("engineering_cost", 0)
    
    if surf_cost > 0:
        draw_appended_row("SURFACE TREATMENT/COATING", _fmt_inr(surf_cost))
    if log_cost > 0:
        draw_appended_row("Internal Logistics, Manufacturing Ops, Rework", _fmt_inr(log_cost))
    if eng_cost > 0:
        draw_appended_row("Engineering Charges", _fmt_inr(eng_cost))

    subtotal_b = total_a + surf_cost + log_cost + eng_cost

    # 3. Total B
    draw_appended_row("TOTAL B", _fmt_inr(subtotal_b))

    # 4. Taxation rows (We do SGST then CGST cleanly)
    sgst = quote_data.get("sgst", subtotal_b * 0.09)
    cgst = quote_data.get("cgst", subtotal_b * 0.09)
    
    # SGST
    draw_appended_row("Taxation C - SGST @ 9%", _fmt_inr(sgst))
    # CGST
    draw_appended_row("Taxation C - CGST @ 9%", _fmt_inr(cgst))

    # 5. Grand Total (Lighter Blue Highlight)
    grand_total = quote_data.get("grand_total", subtotal_b + sgst + cgst)
    lblue = (210, 235, 255) # Light blue matching Image 2 totals
    draw_appended_row("GRAND TOTAL = (A+B+C)", _fmt_inr(grand_total), color=lblue)

    # 6. Amount in Words (Lighter Blue/Green Highlights)
    words = amount_in_words(grand_total)
    lblue_words = (215, 240, 255)
    draw_appended_row(f" Amount in Words: {words}", "", color=lblue_words, is_words=True)

    pdf.ln(10)

    # ── TECHNICAL DATA TABLE ────────────────────────────────────────────────
    pdf._set_font("B", 8)
    pdf.cell(0, 5, "Technical Parameters:", ln=True)
    
    tech_col_w = [12, 20, 45, 23, 90]
    tech_headers = ["Sr. no.", "PART NO.", "DIMENSIONS", "Weight (kg)", "MANUFACTURING PROCESS"]
    pdf.set_fill_color(225, 240, 255) # Light blue
    pdf.set_draw_color(0, 0, 0)
    
    pdf._set_font("B", 7)
    for i, h_text in enumerate(tech_headers):
        pdf.cell(tech_col_w[i], 6, h_text, border=1, align="C", fill=True)
    pdf.ln(6)
    
    pdf._set_font("", 7)
    if parts and len(parts) > 0:
        for idx, part in enumerate(parts, 1):
            part_num = f"RF{quote_number[-4:]}-{idx:02d}"
            dims = part.get("dimensions_str", "-")[:40]
            wt = f"{part.get('weight_kg', 0):.3f}"
            proc = part.get("manufacturing_processes_str", "-")[:100]
            
            pdf.cell(tech_col_w[0], 6, str(idx), border=1, align="C")
            pdf.cell(tech_col_w[1], 6, str(part_num), border=1, align="C")
            pdf.cell(tech_col_w[2], 6, str(dims), border=1, align="C")
            pdf.cell(tech_col_w[3], 6, str(wt), border=1, align="C")
            pdf.cell(tech_col_w[4], 6, str(proc), border=1, align="L")
            pdf.ln(6)
    else:
        part_num = "01"
        bb = quote_data.get("bounding_box", {})
        if "boundingBox" in quote_data: # handle diff schema structures cleanly
            bb = quote_data["boundingBox"]
        dims = f"{bb.get('sizeX', 0):.0f}x{bb.get('sizeY', 0):.0f}x{bb.get('sizeZ', 0):.0f}" if bb else "CAD Data"
        wt = f"{quote_data.get('mass_kg', 0):.3f}"
        proc = quote_data.get("process", "CNC Machining")
        
        pdf.cell(tech_col_w[0], 6, "1", border=1, align="C")
        pdf.cell(tech_col_w[1], 6, part_num, border=1, align="C")
        pdf.cell(tech_col_w[2], 6, dims, border=1, align="C")
        pdf.cell(tech_col_w[3], 6, wt, border=1, align="C")
        pdf.cell(tech_col_w[4], 6, proc, border=1, align="L")
        pdf.ln(6)

    pdf.ln(10)

    # ── TERMS & CONDITIONS ───────────────────────────────────────────────────
    pdf._set_font("B", 8)
    pdf.cell(0, 5, "Terms & Conditions:", ln=True)
    pdf._set_font("", 8)

    terms = [
        "GST @18% against supply order.",
        "Delivery Time within 3 weeks, Inclusive of Transportation.",
        "70% Advance and remaining payment successful quality acceptance by client.",
        "Validity of the above quotation for 15 days.",
        "All disputes are subject to Pune jurisdiction only."
    ]
    for i, t in enumerate(terms, 1):
        pdf.cell(0, 4.5, f"{i}. {t}", ln=True)

    pdf.ln(8)

    # ── SIGNATURE ────────────────────────────────────────────────────────────
    pdf._set_font("", 9)
    pdf.cell(0, 5, "Yours Faithfully,", ln=True)
    pdf.ln(8)
    pdf._set_font("B", 9)
    pdf.cell(0, 5, "For ACCU DESIGN", ln=True)
    pdf.ln(8)
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
        pdf.output(tmp.name)
        
        # Cleanup temporary image file if it exists
        if tmp_img_path and os.path.exists(tmp_img_path):
            try:
                os.remove(tmp_img_path)
            except:
                pass
                
        return tmp.name
